<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Vesper Launcher</Product>
    <Authors>Zayrix and ayush.ue5</Authors>
    <Company>Zayrix and ayush.ue5</Company>
    <Copyright>Copyright (c) 2026 Zayrix and ayush.ue5</Copyright>
    <Version>1.0.2</Version>
  </PropertyGroup>

</Project>
