modLoader = "javafml"
loaderVersion = "[1,)"
license = "LicenseRef-Vesper"
issueTrackerURL = "https://github.com/AroseEditor/Vesper-Launcher/issues"

[[mods]]
modId = "vesper"
version = "${version}"
displayName = "Vesper"
authors = "ayush.ue5"
description = '''
Motion blur, a configurable HUD, cosmetics and offline skin rendering for Vesper Launcher.
'''

[[mixins]]
config = "vesper-common.mixins.json"

[[dependencies.vesper]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.vesper]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,1.22)"
    ordering = "NONE"
    side = "CLIENT"
